#!/usr/bin/env python3
#
# inserter
#
#
# https://docs.microsoft.com/en-us/windows/win32/controls/about-rich-edit-controls

import sys
import os.path
from os import path
from pathlib import Path
import random

args = sys.argv

links = os.environ['HOME'] + '/.links'

def read(file):
    f = open(file, 'r')
    contents = f.read()
    f.close()
    return contents

if(len(args) < 2):
    urls = list(filter(lambda x: x.startswith('http'), read(links).split('\n')))
    url_size = len(urls)
    idx = random.randint(0, url_size - 1)
    print(urls[idx])
    sys.exit()

url = [x for x in args if x.startswith('http')][0]

contents = ''

if(path.exists(links)):
    contents = read(links)
else:
    Path(links).touch()

if(url in contents):
    sys.exit()

f = open(links, 'a')
f.write(url + '\n')
f.close()
