#!/usr/bin/env bash

if [ "$1" == "-b" ]; then
    files=$(find . -perm +111 -type f | grep -v .git)
    len=$(find . -perm +111 -type f | grep -v .git)
else
    files=$(find . -type f | grep -v git | grep -v .class)
    len=$(find . -type f | grep -v git | grep -v .class | wc -l)
fi

idx=$(echo $((1 + RANDOM % $len)))
i=0
target_file=$file
for file in $files; do
    if [ "$i" == "$idx" ]; then
        target_file=$file
    fi
    i=$((i+1))
done
echo $target_file
